/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AudioMediaCard: typeof import('./src/components/AudioMediaCard/index.vue')['default']
    AudioMediaRow: typeof import('./src/components/AudioMediaRow/index.vue')['default']
    ImageMediaCard: typeof import('./src/components/ImageMediaCard/index.vue')['default']
    ImageMediaRow: typeof import('./src/components/ImageMediaRow/index.vue')['default']
    MediaCard: typeof import('./src/components/MediaCard/index.vue')['default']
    MediaRow: typeof import('./src/components/MediaRow/index.vue')['default']
    PreviewImage: typeof import('./src/components/PreviewImage/index.vue')['default']
    PreviewVideo: typeof import('./src/components/PreviewVideo/index.vue')['default']
    SearchInput: typeof import('./src/components/SearchInput/index.vue')['default']
    VideoMediaCard: typeof import('./src/components/VideoMediaCard/index.vue')['default']
    VideoMediaRow: typeof import('./src/components/VideoMediaRow/index.vue')['default']
  }
}
